<?php
// $Id$
/**
 * @file
 * Convert a timestamp into a nice date display.
 * This is mostly an API module at the moment, implement
 * THEMENAME_template_preprocess_node in your theme to override the display of the submission time.
 * TODO: field formatter needs more work
 */

/**
 * Implementation of hook_perm().
 */
function fancy_dates_perm() {
  return array(
    'administer fancy_dates',
  );
}
    
/**
 * Implementation of hook_menu().
 */
function fancy_dates_menu() {
  $items = array();
  $items['admin/settings/fancy_dates'] = array(
    'title' => 'fancy_dates settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('fancy_dates_settings_form'),
    'access arguments' => array('administer fancy_dates'),
  );
  return $items;
}

function fancy_dates_settings_form() {
  $form = array();
  $options = array(
    'day' => array(
      'd' => t('01 to 31'),
      'D' => t('Mon through Sun'),
      'j' => t('1 to 31'),
      'l' => t('Sunday through Saturday'),
      'N' => t('1 through 7'),
      'jS' => t('1st, 2nd, 3rd, 4th etc'),
      'w' => t('0 (Sunday) through 6'),
      'z' => t('0 through 365'),
    ),
    'month' => array(
      'F' => t('January through December'),
      'm' => t('01 through 12'),
      'M' => t('Jan through Dec'),
      'n' => t('1 through 12'),
    ),
    'year' => array(
      'Y' => t('1999 or 2003'),
      'y' => t('99 or 03'),
    ),
  );

  $form['fancy_dates'] = array(
    '#title' => t('Date display'),
    '#type' => 'fieldset',
    '#tree' => TRUE,
  );
  $form['fancy_dates']['day'] = array(
    '#title' => t('Day'),
    '#description' => t(''),
    '#type' => 'select',
    '#options' => $options['day'],
  );
  $form['fancy_dates']['month'] = array(
    '#title' => t('Month'),
    '#description' => t(''),
    '#type' => 'select',
    '#options' => $options['month'],
  );
  $form['fancy_dates']['year'] = array(
    '#title' => t('Year'),
    '#description' => t(''),
    '#type' => 'select',
    '#options' => $options['year'],
  );
  return system_settings_form($form);
}

function fancy_dates_form_alter(&$form, &$form_state, $form_id) {
  if ('node_type_form' == $form_id) {
    $type = $form['#node_type']->type;
    $form['fancy_dates'] = array(
      '#type' => 'fieldset',
      '#title' => t('fancy_dates'),
      '#description' => t('Fancy date display'),
      '#collapsible' => TRUE,
    );

    $form['fancy_dates']['fancy_dates_submitted'] = array(
      '#type' => 'checkbox',
      '#title' => t('Display the date as fancy format'),
      '#default_value' => variable_get('fancy_dates_submitted_' . $type, TRUE),
    );
  }
}

/**
 * Implementation of hook_content_extra_fields().
 */
function fancy_dates_content_extra_fields($type_name) {
  $options = array('query' => drupal_get_destination(), 'fragment' => 'fancy_dates');
  $link = l(t('Configure'), 'admin/content/node-type/' . $type_name, $options); 

  $extras = array();
  if (variable_get('fancy_dates_submitted_' . $type_name, TRUE)) {
    $extras['fancy_dates_submitted'] = array(
      'label' => t('Submitted on'),
      'description' => t('Timestamp for the node.'),
      'weight' => -5,
      'configure' => $link,
    );
  }
  return $extras;
}

/**
 * Implementation of hook_nodeapi().
 */
function fancy_dates_nodeapi(&$node, $op, $teaser, $page) {
  if ('view' == $op) {
    if (variable_get('fancy_dates_submitted_' . $node->type, TRUE)) {
      $weight = content_extra_field_weight($node->type, 'fancy_dates_submitted');
      $created = theme('fancy_dates_timestamp', $node->created);
      $node->content['fancy_dates_submitted'] = array(
        '#weight' => !empty($weight) ? $weight : -5,
        '#value' => theme('fancy_dates_timestamp', $node->created),
      );
    }
  }
}

/**
 * Implementation of hook_theme().
 */
function fancy_dates_theme() {
  return array(
    'fancy_dates_timestamp' => array(
      'arguments' => array('timestamp' => NULL),
      'template' => 'fancy_dates',
    ),
    'fancy_dates_string' => array(
      'arguments' => array('datestring' => NULL),
      'template' => 'fancy_dates',
    ),
    'fancy_dates_formatter_default' => array(
      'arguments' => array('element' => NULL),
    ),
  );
}

// TODO check programmatically if its an int perhaps or a string?
// Date fields output a string.
// Node submitted and other timesatmps are integers, it would be nice to support both.

/**
 * Create a fancy date out of a timestamp.
 */
function template_preprocess_fancy_dates_timestamp(&$variables) {
  $variables = array_merge($variables, fancy_date($variables['timestamp']));
}

/**
 * Create a fancy date out of a time string.
 */
function template_preprocess_fancy_dates_string(&$variables) {
  $timestamp = strtotime($variables['datestring']);
  $variables = array_merge($variables, fancy_date($timestamp));
}

/**
 * Take an integer timestamp and break it down to day, month and year.
 */
function fancy_date($timestamp) {
  $day_format = variable_get('fancy_dates_day', 'j');
  $month_format = variable_get('fancy_dates_motnh', 'M');
  $year_format = variable_get('fancy_dates_year', 'Y');

  $date = array(
    'day' => format_date($timestamp, 'custom', $day_format),
    'month' => format_date($timestamp, 'custom', $month_format),
    'year' => format_date($timestamp, 'custom', $year_format),
  );
  return $date;
}

/**
  * Implementation of hook_field_formatter_info().
 */
function fancy_dates_field_formatter_info() {
  $formatters = array();
  $formatters['default'] = array(
    'label' => t('fancy_dates'),
    'field types' => array('date', 'date_format', 'created', 'changed'),
  );
  return $formatters;
}

function theme_fancy_dates_formatter_default($element) {
  return theme('fancy_dates_string', $element['#item']['value']);
}

